version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    network_mode: host